[package]
name = "rust-the-book"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = 'abort' # abort without unwind the stack in release mode

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
